/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import processing.core.PApplet;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void simpleTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }

    @Test
    public void allTest2(){
        App app = new App();
        GameManager manager = new GameManager("config2.json");
        app.manager = manager;
        PApplet.runSketch(new String[]{""}, app);  
        app.delay(4000);

    }

    @Test
    public void testShowWinnerWaka(){
        App app = new App();
        GameManager manager = new GameManager("config2.json");
        app.manager = manager;
        
        manager.setWinner(Winner.WAKA);
        PApplet.runSketch(new String[]{"get HD in 1113"}, app); 
        app.delay(1000);
    }

    @Test
    public void testShowWinnerGhost(){
        App app = new App();
        GameManager manager = new GameManager("config2.json");
        app.manager = manager;
        
        manager.setWinner(Winner.GHOST);
        PApplet.runSketch(new String[]{""}, app); 
    }
}

